# ========================================================================================
# Exercice 1a : Entra ID — Création unitaire d'un utilisateur via Graph API
# ========================================================================================
# Concept : Provisioning d'un utilisateur unique via Microsoft Graph (SDK PowerShell).
# Pas de CSV, pas de boucle — un seul compte, créé manuellement avec splatting.
#
# Ce que fait ce script :
#   1. Reset total de session
#   2. Recherche un UPN disponible (auto-incrément)
#   3. Génère un mot de passe aléatoire sécurisé
#   4. Configure et crée l'utilisateur via New-MgUser
#   5. Vérifie la création depuis la source de vérité (Get-MgUser)
#   6. Ferme proprement toutes les sessions
#
# Contexte test : "Geralt de Riv" — personnage Witcher utilisé comme jeu de données
# représentatif sur le tenant de dev (0n4mg.onmicrosoft.com).
#
# Module requis : Microsoft.Graph.Users
# Connexion     : Connect-MgGraph
# ========================================================================================

# --- OUVERTURE — RESET DE SESSION TOTAL ---
# REX : une session MgGraph résiduelle (contexte précédent, scopes insuffisants)
# peut provoquer des erreurs 403 silencieuses ou des authentifications croisées.
# On déconnecte proprement avant toute reconnexion.
#
# Note : Disconnect-MgGraph ne génère pas d'erreur si aucune session n'est active —
# -ErrorAction SilentlyContinue est là par précaution.
Disconnect-MgGraph -ErrorAction SilentlyContinue
Connect-MgGraph -Scopes "User.ReadWrite.All"

# ========================================================================================
# ÉTAPE 1 : Recherche d'un UPN disponible (auto-incrément)
# ========================================================================================
Write-Host "1. Recherche d'un UPN disponible..." -ForegroundColor Cyan

# DÉCOUVERTE TECHNIQUE : Graph ne lève pas d'erreur explicite à la création si
# l'UPN existe déjà — il retourne un conflit HTTP 409 encapsulé dans une exception.
# On préfère tester l'existence en amont avec Get-MgUser plutôt que gérer le catch.
$BaseUPN     = "geralt"
$Domain      = "@0n4mg.onmicrosoft.com"
$UPNSuffix   = $BaseUPN
$Counter     = 2
while (Get-MgUser -UserId "$UPNSuffix$Domain" -ErrorAction SilentlyContinue) {
    Write-Host "   '$UPNSuffix$Domain' déjà pris — test avec suffixe -v$Counter..." -ForegroundColor Yellow
    $UPNSuffix = "$BaseUPN-v$Counter"
    $Counter++
}
$FinalUPN = "$UPNSuffix$Domain"
Write-Host "-> UPN retenu : '$FinalUPN'`n" -ForegroundColor Green

# ========================================================================================
# ÉTAPE 2 : Génération du mot de passe temporaire
# ========================================================================================
Write-Host "2. Génération du mot de passe temporaire..." -ForegroundColor Cyan

# Jeu de caractères volontairement limité : pas de caractères ambigus (0/O, 1/l/I)
# ni de caractères spéciaux pouvant poser problème dans certains formulaires AAD.
# 16 caractères = compromis lisibilité / entropie suffisante pour un compte de dev.
$Chars                = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!@#$"
$AutoGeneratedPassword = -join (1..16 | ForEach-Object { $Chars.ToCharArray() | Get-Random })

# ForceChangePasswordNextSignIn = $true : bonne pratique même sur tenant de dev.
# L'utilisateur devra changer son mot de passe à la première connexion.
# Cela évite qu'un mot de passe auto-généré reste actif indéfiniment.
$PasswordProfile = @{
    Password                      = $AutoGeneratedPassword
    ForceChangePasswordNextSignIn = $true
}
Write-Host "-> Mot de passe temporaire généré (non affiché).`n" -ForegroundColor Green

# ========================================================================================
# ÉTAPE 3 : Création de l'utilisateur
# ========================================================================================
Write-Host "3. Création de l'utilisateur '$FinalUPN'..." -ForegroundColor Cyan

# Splatting : technique PowerShell qui passe un hashtable comme ensemble de paramètres.
# Plus lisible qu'une longue ligne avec des backticks, plus maintenable.
#
# Country / Department : ces propriétés ne sont pas retournées par défaut par Graph.
# Il faut les demander explicitement via -Property à la lecture (voir étape 4).
# Elles sont utiles pour les Unités Administratives dynamiques et les groupes
# dynamiques qui filtrent sur ces attributs.
$UserParams = @{
    DisplayName       = "Geralt de Riv"
    MailNickName      = $UPNSuffix
    UserPrincipalName = $FinalUPN
    AccountEnabled    = $true
    PasswordProfile   = $PasswordProfile
    Country           = "France"
    Department        = "SecOps"
}

$NewUser = New-MgUser @UserParams
if (-not $NewUser) {
    Write-Host "-> Échec de la création de l'utilisateur." -ForegroundColor Red
    Disconnect-MgGraph -ErrorAction SilentlyContinue
    return
}
Write-Host "-> Utilisateur créé : $($NewUser.DisplayName) [$($NewUser.Id)]`n" -ForegroundColor Green

# ========================================================================================
# ÉTAPE 4 : Vérification depuis la source de vérité
# ========================================================================================
Write-Host "4. Vérification depuis le backend Graph..." -ForegroundColor Cyan

# DÉCOUVERTE TECHNIQUE : Country et Department ne sont PAS retournés dans la réponse
# immédiate de New-MgUser, et ne figurent pas dans les propriétés par défaut de
# Get-MgUser. Deux contraintes s'accumulent :
#   - La propagation Graph n'est pas instantanée (latence backend ~1s minimum)
#   - Il faut passer -Property explicitement pour obtenir ces champs
# Sans le Start-Sleep, Country et Department reviennent vides même si la création a réussi.
Start-Sleep -Seconds 30

$CheckUser = Get-MgUser -UserId $FinalUPN `
    -Property "id,displayName,userPrincipalName,country,department,accountEnabled" `
    -ErrorAction SilentlyContinue

if ($CheckUser) {
    Write-Host "-> Utilisateur confirmé :" -ForegroundColor Green
    [PSCustomObject]@{
        Id                = $CheckUser.Id
        DisplayName       = $CheckUser.DisplayName
        UPN               = $CheckUser.UserPrincipalName
        AccountEnabled    = $CheckUser.AccountEnabled
        Country           = $CheckUser.Country
        Department        = $CheckUser.Department
    } | Format-List
} else {
    Write-Host "-> ATTENTION : utilisateur non trouvé lors de la vérification." -ForegroundColor Red
}

# ========================================================================================
# ÉTAPE 5 : Résumé
# ========================================================================================
Write-Host "=== RÉSUMÉ ===" -ForegroundColor Magenta
[PSCustomObject]@{
    UPNCréé          = $FinalUPN
    DisplayName      = "Geralt de Riv"
    MotDePasse       = "Temporaire (ForceChangePasswordNextSignIn = true)"
    Country          = "France"
    Department       = "SecOps"
    StatutCompte     = if ($CheckUser) { "Confirmé dans Graph" } else { "Non vérifié" }
} | Format-List

# ========================================================================================
# NETTOYAGE MÉMOIRE
# ========================================================================================
Remove-Variable BaseUPN, Domain, UPNSuffix, Counter, FinalUPN,
                Chars, AutoGeneratedPassword, PasswordProfile,
                UserParams, NewUser, CheckUser `
                -ErrorAction SilentlyContinue

# ========================================================================================
# FERMETURE — RESET DE SESSION TOTAL
# ========================================================================================
Disconnect-MgGraph -ErrorAction SilentlyContinue
Write-Host "Session MgGraph fermée proprement." -ForegroundColor Magenta
