# ==============================================================================
# EXERCICE 2 : Création unitaire d'un utilisateur
# Objectif : Provisioning unitaire d'un utilisateur via Graph API.
# ==============================================================================

# Connexion avec les privilèges requis pour la gestion des comptes
Connect-MgGraph -Scopes "User.ReadWrite.All"

# 1. Génération standard et lisible du mot de passe (16 caractères)
$Chars = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!@#$"
$AutoGeneratedPassword = -join (1..16 | ForEach-Object { $Chars.ToCharArray() | Get-Random })

# 2. Configuration du profil de mot de passe
$PasswordProfile = @{
    Password                      = $AutoGeneratedPassword
    ForceChangePasswordNextSignIn = $true
}

# 3. Paramètres de l'utilisateur (Splatting)
$UserParams = @{
    DisplayName       = "Geralt de Riv"
    MailNickName      = "geralt"
    UserPrincipalName = "geralt@0n4mg.onmicrosoft.com"
    AccountEnabled    = $true
    PasswordProfile   = $PasswordProfile
    Country           = "France"   # Utilisé pour le ciblage dynamique de l'AU
    Department        = "SecOps"   # Idéal pour croiser les critères plus tard
}

# 4. Exécution et création dans Entra ID
$NewUser = New-MgUser @UserParams
if (-not $NewUser) { Write-Error "La création de l'utilisateur a échoué." ; return }

# 5. Affichage du résultat pour validation dans la console
$NewUser | Select-Object Id, DisplayName, UserPrincipalName, Country, Department

# 6. Ne pays et le Departement ne passent pas immédiatement. On force Azuer a attendre 1 seconde 
Start-Sleep -Seconds 1

# 7. Puis on le force à afficher la personne encore une fois
Get-MgUser -UserId "geralt@0n4mg.onmicrosoft.com" -Property "id,displayName,country,department" | Select-Object Id, DisplayName, Country, Department

# 8. Nettoyage de la session (Zéro résidu en mémoire)
Remove-Variable Chars, AutoGeneratedPassword, PasswordProfile, UserParams, NewUser
