# ==============================================================================
# EXERCICE 2bis : Industrialisation et création d'utilisateurs en masse (Bulk)
# Emplacement lab : D:\Documents\ScriptsPowerShell
# Objectif : Importer utilisateurs.csv et provisionner les comptes à la volée.
# Concepts clés : Import-Csv, Boucle ForEach, Splatting dynamique, Try/Catch.
# ==============================================================================

# 1. Connexion à l'API Microsoft Graph avec les privilèges d'écriture
Connect-MgGraph -Scopes "User.ReadWrite.All"

# 2. Définition du chemin du fichier CSV - WARNING - a decommenter la ligne necessaire : 
# EN LABO/Local :
 $PathCSV = "D:\Documents\ScriptsPowerShell\utilisateurs.csv"

# EN PRODUCTION : 
# $PathCSV = "$PSScriptRoot\utilisateurs.csv"

# Vérification de sécurité : On s'assure que le fichier CSV est bien présent dans le dossier
if (-not (Test-Path $PathCSV)) {
    Write-Error "Erreur : Le fichier 'utilisateurs.csv' est introuvable dans $PathCSV !"
    exit
}

# 3. Importation et lecture du fichier CSV (Séparateur : virgule, encodage UTF8 via Notepad++)
$UsersToCreate = Import-Csv -Path $PathCSV -Delimiter ","

# Pool de caractères pour la génération des mots de passe aléatoires
$Chars = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!@#$"

Write-Host "--- Début du Provisioning en Masse ($($UsersToCreate.Count) comptes détectés) ---`n" -ForegroundColor Cyan

# 4. Traitement ligne par ligne du CSV via la boucle foreach
foreach ($User in $UsersToCreate) {
    
    # Génération d'un mot de passe unique et complexe pour CHAQUE utilisateur (16 caractères)
    $AutoGeneratedPassword = -join (1..16 | ForEach-Object { $Chars.ToCharArray() | Get-Random })
    
    $PasswordProfile = @{
        Password                      = $AutoGeneratedPassword
        ForceChangePasswordNextSignIn = $true
    }

    # 5. Splatting dynamique : On mappe les colonnes du CSV ($User.NomDeLaColonne)
    $UserParams = @{
        DisplayName       = $User.DisplayName
        MailNickName      = $User.MailNickName
        UserPrincipalName = $User.UserPrincipalName
        AccountEnabled    = $true
        PasswordProfile   = $PasswordProfile
        Country           = $User.Country
        Department        = $User.Department
    }

    # 6. Bloc de sécurité Try/Catch pour gérer les erreurs d'exécution (ex: doublons)
    try {
        # Exécution de la création dans Entra ID
        $NewUser = New-MgUser @UserParams
        
        # Log de succès en vert dans la console
        Write-Host "[SUCCESS] Compte créé : $($NewUser.UserPrincipalName) | Password : $AutoGeneratedPassword" -ForegroundColor Green
    }
    catch {
        # Si une ligne plante, on affiche l'erreur en rouge et le script passe à la suite
        Write-Host "[ERROR] Échec pour $($User.UserPrincipalName) : $_" -ForegroundColor Red
    }
}

Write-Host "`n--- Fin du traitement automatique ---" -ForegroundColor Cyan

# 7. Nettoyage de la mémoire (Zéro résidu de variables en fin d'exécution)
Remove-Variable PathCSV, UsersToCreate, Chars, AutoGeneratedPassword, PasswordProfile, UserParams -ErrorAction SilentlyContinue
